<a href="https://colab.research.google.com/github/sunzdinh/API-webmovie/blob/main/Deep_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install numpy
import numpy as np


In [9]:
#cau1
a = np.random.randint(20, size=(3,3))
print(a)
result = np.all(a)
print(result)

[[ 1 19 10]
 [11 17  9]
 [16  4  5]]
True


In [10]:
a = np.random.randint(20, size=(3,3))
print(a)
result= np.any(a)
print(result)

[[ 3 17  8]
 [ 5 11  7]
 [ 7 15  7]]
True
